import React, { useState, useRef } from 'react';
import { EmbeddingSettings } from '../../shared/types';
import { uploadBrandingLogo } from '../../api/settingsApi';
import { isImageUrl } from '../../shared/utils/branding';
import { showToast } from '../../stores/useToastStore';
import { useSettingsStore } from '../../stores/useSettingsStore';
import { MasterKeyModal } from './MasterKeyModal';

export interface GeneralTabProps {
  settings: EmbeddingSettings | null;
  saveEmbeddingSettings: (settings: EmbeddingSettings) => Promise<boolean>;
  setMasterKey?: (newKey: string) => Promise<{ success: boolean; message?: string; error?: string }>;
}

export const GeneralTab: React.FC<GeneralTabProps> = ({ settings, saveEmbeddingSettings, setMasterKey }) => {
  return <GeneralTabForm key={JSON.stringify(settings)} settings={settings} saveEmbeddingSettings={saveEmbeddingSettings} setMasterKey={setMasterKey} />;
};

const GeneralTabForm: React.FC<GeneralTabProps> = ({ settings, saveEmbeddingSettings, setMasterKey }) => {
  const [dashboardTitle, setDashboardTitle] = useState(settings?.dashboardTitle ?? 'Model Context Gateway');
  const [dashboardIcon, setDashboardIcon] = useState(settings?.dashboardIcon ?? 'fa-solid fa-network-wired');
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [embProvider, setEmbProvider] = useState(settings?.embeddingProvider ?? 'local');
  const [embModelDir, setEmbModelDir] = useState(settings?.embeddingModelDir ?? 'data/models');
  const [embApiUrl, setEmbApiUrl] = useState(settings?.embeddingApiUrl ?? 'http://litellm:4000/v1/embeddings');
  const [embApiModel, setEmbApiModel] = useState(settings?.embeddingApiModel ?? 'all-MiniLM-L6-v2');
  const [embApiKey, setEmbApiKey] = useState(settings?.embeddingApiKey ?? '');
  const [allowOpenDCR, setAllowOpenDCR] = useState(settings?.allowOpenClientRegistration ?? true);
  const [userMaxKeys, setUserMaxKeys] = useState<number>(settings?.userMaxKeys ?? 5);
  const [globalMaxKeys, setGlobalMaxKeys] = useState<number>(settings?.globalMaxKeys ?? 100);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [isMasterKeyModalOpen, setIsMasterKeyModalOpen] = useState(false);

  const masterKeySource = settings?.masterKeySource || 'AutoGenerated';

  const handleSetMasterKey = async (newKey: string) => {
    if (setMasterKey) {
      return await setMasterKey(newKey);
    }
    return await useSettingsStore.getState().setMasterKey(newKey);
  };

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setIsUploading(true);
    try {
      const res = await uploadBrandingLogo(file);
      if (res && res.success && res.url) {
        setDashboardIcon(res.url);
        showToast('Logo image uploaded successfully.', 'success');
      } else {
        showToast('Failed to upload logo image.', 'error');
      }
    } catch (err: any) {
      showToast(err.message || 'Failed to upload logo image.', 'error');
    } finally {
      setIsUploading(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const handleSaveSearchSettings = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaveStatus('saving');
    const success = await saveEmbeddingSettings({
      dashboardTitle,
      dashboardIcon,
      embeddingProvider: embProvider,
      embeddingModelDir: embModelDir,
      embeddingApiUrl: embApiUrl,
      embeddingApiModel: embApiModel,
      embeddingApiKey: embApiKey,
      allowOpenClientRegistration: allowOpenDCR,
      userMaxKeys: Number(userMaxKeys),
      globalMaxKeys: Number(globalMaxKeys),
    });
    setSaveStatus(success ? 'saved' : 'error');
    setTimeout(() => setSaveStatus('idle'), 2500);
  };

  return (
    <div id="subview-search" data-testid="general-tab" className="settings-subview active">
      <div className="glass-card settings-card" style={{ maxWidth: '600px', margin: '0 auto' }}>
        <h2>
          <i className="fa-solid fa-gear"></i> General Settings
        </h2>
        <p className="description" style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '20px' }}>
          Configure branding and semantic search settings. Changes are saved securely to the database.
        </p>

        {/* Master Key Status Banner */}
        {masterKeySource === 'AutoGenerated' && (
          <div
            className="alert alert-warning master-key-banner"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '12px 16px',
              marginBottom: '20px',
              borderRadius: '8px',
              background: 'rgba(234, 179, 8, 0.1)',
              border: '1px solid rgba(234, 179, 8, 0.3)',
              color: '#fef08a',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <i className="fa-solid fa-triangle-exclamation" style={{ fontSize: '18px', color: '#eab308' }}></i>
              <div>
                <strong style={{ display: 'block', fontSize: '13px', color: '#fef08a' }}>Auto-Generated Master Key in Use</strong>
                <span style={{ fontSize: '12px', color: '#fef9c3', opacity: 0.9 }}>
                  The gateway is using an ephemeral auto-generated master key. Configure a permanent master key for disaster recovery.
                </span>
              </div>
            </div>
            <button
              type="button"
              id="btn-open-master-key-modal"
              data-testid="btn-open-master-key-modal"
              className="btn btn-primary btn-sm"
              onClick={() => setIsMasterKeyModalOpen(true)}
              style={{ whiteSpace: 'nowrap', marginLeft: '12px' }}
            >
              <i className="fa-solid fa-key"></i> Set Custom Master Key
            </button>
          </div>
        )}

        {(masterKeySource === 'External' || masterKeySource === 'Vault' || masterKeySource === 'SecretFile') && (
          <div
            className="master-key-banner"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '10px 14px',
              marginBottom: '20px',
              borderRadius: '8px',
              background: 'rgba(59, 130, 246, 0.08)',
              border: '1px solid rgba(59, 130, 246, 0.2)',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <i className="fa-solid fa-shield-halved" style={{ fontSize: '16px', color: '#38bdf8' }}></i>
              <div>
                <strong style={{ fontSize: '13px', color: '#e2e8f0' }}>Master Encryption Key</strong>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Database secrets are encrypted with external key management.</div>
              </div>
            </div>
            <span
              className="badge badge-secondary"
              style={{
                fontSize: '11px',
                display: 'flex',
                alignItems: 'center',
                gap: '5px',
                padding: '4px 10px',
                background: 'rgba(255,255,255,0.08)',
                border: '1px solid rgba(255,255,255,0.15)',
              }}
            >
              <i className="fa-solid fa-lock"></i> Managed externally ({masterKeySource === 'Vault' ? 'Vault' : 'Vault / Environment'})
            </span>
          </div>
        )}

        {masterKeySource === 'Configured' && (
          <div
            className="master-key-banner"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '10px 14px',
              marginBottom: '20px',
              borderRadius: '8px',
              background: 'rgba(16, 185, 129, 0.08)',
              border: '1px solid rgba(16, 185, 129, 0.2)',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <i className="fa-solid fa-shield-halved" style={{ fontSize: '16px', color: '#34d399' }}></i>
              <div>
                <strong style={{ fontSize: '13px', color: '#e2e8f0' }}>Master Encryption Key</strong>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Custom permanent master encryption key active.</div>
              </div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span
                className="badge badge-success"
                style={{
                  fontSize: '11px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '5px',
                  padding: '4px 10px',
                  background: 'rgba(16, 185, 129, 0.2)',
                  color: '#34d399',
                  border: '1px solid rgba(16, 185, 129, 0.3)',
                }}
              >
                <i className="fa-solid fa-circle-check"></i> Configured
              </span>
              <button
                type="button"
                id="btn-rotate-master-key"
                data-testid="btn-rotate-master-key"
                className="btn btn-secondary btn-sm"
                onClick={() => setIsMasterKeyModalOpen(true)}
                style={{ fontSize: '11px', padding: '3px 8px' }}
              >
                <i className="fa-solid fa-rotate"></i> Rotate Key
              </button>
            </div>
          </div>
        )}
        <form id="settings-form" onSubmit={handleSaveSearchSettings}>
          
          <div className="form-group">
            <h3 style={{ fontSize: '14px', marginBottom: '10px', marginTop: '10px', color: 'var(--primary)' }}>Dashboard Branding</h3>
          </div>
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="settings-dashboard-title">Dashboard Title</label>
              <input
                type="text"
                id="settings-dashboard-title"
                data-testid="settings-dashboard-title"
                placeholder="Model Context Gateway"
                value={dashboardTitle}
                onChange={(e) => setDashboardTitle(e.target.value)}
              />
            </div>
            <div className="form-group">
              <label htmlFor="settings-dashboard-icon">Header Icon or Logo URL (FontAwesome class or Image URL)</label>
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <input
                  type="text"
                  id="settings-dashboard-icon"
                  data-testid="settings-dashboard-icon"
                  placeholder="fa-solid fa-network-wired"
                  value={dashboardIcon}
                  onChange={(e) => setDashboardIcon(e.target.value)}
                  style={{ flex: 1 }}
                />
                <input
                  type="file"
                  ref={fileInputRef}
                  id="settings-dashboard-icon-file"
                  accept="image/png,image/jpeg,image/svg+xml,image/webp,image/x-icon"
                  style={{ display: 'none' }}
                  onChange={handleLogoUpload}
                />
                <button
                  type="button"
                  data-testid="btn-upload-logo"
                  className="btn btn-secondary btn-sm"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isUploading}
                  style={{ whiteSpace: 'nowrap' }}
                >
                  <i className={isUploading ? "fa-solid fa-spinner fa-spin" : "fa-solid fa-upload"}></i> {isUploading ? 'Uploading...' : 'Upload Image'}
                </button>
              </div>
              <div className="logo-preview-container" style={{ marginTop: '8px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', color: 'var(--text-muted)' }}>
                <span>Preview:</span>
                <div className="logo-preview-box" style={{ width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: '6px', border: '1px solid rgba(255,255,255,0.1)' }}>
                  {dashboardIcon && isImageUrl(dashboardIcon) ? (
                    <img
                      src={dashboardIcon}
                      alt="Logo Preview"
                      className="logo-icon logo-img"
                      style={{ maxWidth: '28px', maxHeight: '28px', objectFit: 'contain' }}
                    />
                  ) : (
                    <i
                      className={`${dashboardIcon || 'fa-solid fa-network-wired'} logo-icon`}
                      style={{ fontSize: '18px', color: 'var(--primary)' }}
                    ></i>
                  )}
                </div>
                <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                  {dashboardIcon && isImageUrl(dashboardIcon) ? 'Image Logo' : 'FontAwesome Icon'}
                </span>
              </div>
            </div>
          </div>
          
          <div className="form-group">
            <h3 style={{ fontSize: '14px', marginBottom: '10px', marginTop: '20px', color: 'var(--primary)' }}>Semantic Search</h3>
          </div>
          <div className="form-group">
            <label htmlFor="settings-provider">Embedding Provider</label>
            <select
              id="settings-provider"
              value={embProvider}
              onChange={(e) => setEmbProvider(e.target.value)}
              required
            >
              <option value="local">Local ONNX Model (In-Process, CPU-Friendly)</option>
              <option value="api">External Embedding API (LiteLLM, Open WebUI, OpenAI)</option>
            </select>
          </div>

          {embProvider === 'local' ? (
            <div id="settings-local-group">
              <div className="form-group">
                <label htmlFor="settings-model-dir">Local Model Directory (inside volume)</label>
                <input
                  type="text"
                  id="settings-model-dir"
                  placeholder="data/models"
                  value={embModelDir}
                  onChange={(e) => setEmbModelDir(e.target.value)}
                />
                <small style={{ color: 'var(--text-muted)' }}>
                  The <code>all-MiniLM-L6-v2</code> ONNX files will be downloaded automatically to this directory on first run.
                </small>
              </div>
            </div>
          ) : (
            <div id="settings-api-group">
              <div className="form-group">
                <label htmlFor="settings-api-url">Embedding API URL</label>
                <input
                  type="text"
                  id="settings-api-url"
                  placeholder="http://litellm:4000/v1/embeddings"
                  value={embApiUrl}
                  onChange={(e) => setEmbApiUrl(e.target.value)}
                />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="settings-api-model">API Model Name</label>
                  <input
                    type="text"
                    id="settings-api-model"
                    placeholder="all-MiniLM-L6-v2"
                    value={embApiModel}
                    onChange={(e) => setEmbApiModel(e.target.value)}
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="settings-api-key">API Key (Optional)</label>
                  <input
                    type="password"
                    id="settings-api-key"
                    placeholder="API password / auth token"
                    value={embApiKey}
                    onChange={(e) => setEmbApiKey(e.target.value)}
                  />
                </div>
              </div>
            </div>
          )}
          
          <div className="form-group">
            <h3 style={{ fontSize: '14px', marginBottom: '10px', marginTop: '20px', color: 'var(--primary)' }}><i className="fa-solid fa-shield-halved"></i> Security Defaults</h3>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="settings-user-max-keys">Default User Quota (UserMaxKeys)</label>
              <input
                type="number"
                id="settings-user-max-keys"
                min="0"
                placeholder="5"
                value={userMaxKeys}
                onChange={(e) => setUserMaxKeys(parseInt(e.target.value, 10) || 0)}
              />
              <small style={{ color: 'var(--text-muted)' }}>
                Default maximum personal App Keys per user (0 = unlimited).
              </small>
            </div>
            <div className="form-group">
              <label htmlFor="settings-global-max-keys">Global Max Keys</label>
              <input
                type="number"
                id="settings-global-max-keys"
                min="0"
                placeholder="100"
                value={globalMaxKeys}
                onChange={(e) => setGlobalMaxKeys(parseInt(e.target.value, 10) || 0)}
              />
              <small style={{ color: 'var(--text-muted)' }}>
                Maximum total active App Keys allowed across all users (0 = unlimited).
              </small>
            </div>
          </div>
          
          <div className="form-group" style={{ backgroundColor: 'rgba(255,255,255,0.02)', padding: '15px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', margin: 0 }}>
              <input
                type="checkbox"
                id="settings-allow-dcr"
                data-testid="settings-allow-dcr-checkbox"
                checked={allowOpenDCR}
                onChange={(e) => setAllowOpenDCR(e.target.checked)}
                style={{ width: '18px', height: '18px', margin: 0, cursor: 'pointer' }}
              />
              <strong style={{ fontSize: '14px', color: '#e2e8f0' }}>Allow Open Dynamic Client Registration (RFC 7591)</strong>
            </label>
            <p style={{ margin: '8px 0 0 28px', fontSize: '12px', color: 'var(--text-muted)' }}>
              If enabled, third-party clients (like Gemini Spark) can programmatically register themselves via <code>/api/register</code> without requiring an Admin AppKey.
            </p>
          </div>

          <div className="settings-actions" style={{ marginTop: '25px', display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
            <button
              type="submit"
              className="btn btn-primary"
              id="btn-save-settings"
              data-testid="btn-save-general-settings"
              disabled={saveStatus === 'saving'}
              style={{
                backgroundColor: saveStatus === 'saved' ? '#10b981' : saveStatus === 'error' ? '#ef4444' : '',
              }}
            >
              {saveStatus === 'saving' && (
                <>
                  <i className="fa-solid fa-spinner fa-spin"></i> Saving...
                </>
              )}
              {saveStatus === 'saved' && (
                <>
                  <i className="fa-solid fa-check"></i> Saved!
                </>
              )}
              {saveStatus === 'error' && (
                <>
                  <i className="fa-solid fa-triangle-exclamation"></i> Error
                </>
              )}
              {saveStatus === 'idle' && (
                <>
                  <i className="fa-solid fa-floppy-disk"></i> Save Settings
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      <MasterKeyModal
        isOpen={isMasterKeyModalOpen}
        onClose={() => setIsMasterKeyModalOpen(false)}
        onSetMasterKey={handleSetMasterKey}
      />
    </div>
  );
};

